export const categories = [
  { id: "grocery", name: "Groceries", emoji: "🛒", color: "bg-green-50 text-green-700" },
  { id: "cosmetics", name: "Cosmetics", emoji: "💄", color: "bg-pink-50 text-pink-700" },
  { id: "stationery", name: "Stationery", emoji: "📚", color: "bg-blue-50 text-blue-700" },
  { id: "household", name: "Household", emoji: "🏠", color: "bg-yellow-50 text-yellow-700" },
  { id: "hosiery", name: "Hosiery", emoji: "🧦", color: "bg-purple-50 text-purple-700" },
  { id: "gifts", name: "Gifts", emoji: "🎁", color: "bg-red-50 text-red-700" },
  { id: "dairy", name: "Dairy & Eggs", emoji: "🥛", color: "bg-orange-50 text-orange-700" },
  { id: "snacks", name: "Snacks", emoji: "🍿", color: "bg-amber-50 text-amber-700" },
];

export const stores = [
  {
    id: "store-1",
    name: "Sharma Kirana Store",
    owner: "Rajesh Sharma",
    category: "grocery",
    categories: ["grocery", "dairy", "snacks"],
    address: "12, Nehru Colony, Sector 15",
    area: "Sector 15",
    city: "Noida",
    distance: "0.3 km",
    rating: 4.8,
    reviewCount: 312,
    deliveryTime: "10–15 min",
    minOrder: 50,
    deliveryFee: 0,
    isOpen: true,
    isFeatured: true,
    tags: ["Top Rated", "Free Delivery"],
    image: "🏪",
    coverColor: "from-green-400 to-green-600",
    products: [
      { id: "p1", name: "Amul Butter 500g", price: 285, mrp: 300, category: "dairy", unit: "500g", inStock: true, emoji: "🧈" },
      { id: "p2", name: "Tata Salt 1kg", price: 22, mrp: 25, category: "grocery", unit: "1kg", inStock: true, emoji: "🧂" },
      { id: "p3", name: "Aashirvaad Atta 5kg", price: 248, mrp: 270, category: "grocery", unit: "5kg", inStock: true, emoji: "🌾" },
      { id: "p4", name: "Mother Dairy Milk 500ml", price: 28, mrp: 30, category: "dairy", unit: "500ml", inStock: true, emoji: "🥛" },
      { id: "p5", name: "Lay's Classic Salted", price: 20, mrp: 20, category: "snacks", unit: "26g", inStock: true, emoji: "🍿" },
      { id: "p6", name: "Britannia Good Day 75g", price: 15, mrp: 15, category: "snacks", unit: "75g", inStock: false, emoji: "🍪" },
      { id: "p7", name: "Fortune Sunflower Oil 1L", price: 155, mrp: 170, category: "grocery", unit: "1L", inStock: true, emoji: "🫙" },
      { id: "p8", name: "Eggs (12 pcs)", price: 90, mrp: 96, category: "dairy", unit: "12 pcs", inStock: true, emoji: "🥚" },
    ],
  },
  {
    id: "store-2",
    name: "Priya Cosmetics",
    owner: "Priya Verma",
    category: "cosmetics",
    categories: ["cosmetics", "hosiery"],
    address: "Shop 5, Market Complex, Sector 18",
    area: "Sector 18",
    city: "Noida",
    distance: "0.7 km",
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: "15–20 min",
    minOrder: 200,
    deliveryFee: 25,
    isOpen: true,
    isFeatured: true,
    tags: ["Popular"],
    image: "💄",
    coverColor: "from-pink-400 to-rose-500",
    products: [
      { id: "p9", name: "Lakme Kajal", price: 189, mrp: 210, category: "cosmetics", unit: "1 pc", inStock: true, emoji: "👁️" },
      { id: "p10", name: "Nivea Moisturizer 200ml", price: 245, mrp: 275, category: "cosmetics", unit: "200ml", inStock: true, emoji: "🧴" },
      { id: "p11", name: "Dove Soap (3 pack)", price: 120, mrp: 135, category: "cosmetics", unit: "3x100g", inStock: true, emoji: "🧼" },
      { id: "p12", name: "Head & Shoulders 200ml", price: 165, mrp: 180, category: "cosmetics", unit: "200ml", inStock: true, emoji: "💆" },
      { id: "p13", name: "Cotton Socks (6 pair)", price: 180, mrp: 220, category: "hosiery", unit: "6 pairs", inStock: true, emoji: "🧦" },
    ],
  },
  {
    id: "store-3",
    name: "Gupta Stationery & Gifts",
    owner: "Mohan Gupta",
    category: "stationery",
    categories: ["stationery", "gifts"],
    address: "45, School Road, Block C",
    area: "Block C",
    city: "Noida",
    distance: "1.1 km",
    rating: 4.5,
    reviewCount: 97,
    deliveryTime: "20–25 min",
    minOrder: 100,
    deliveryFee: 20,
    isOpen: true,
    isFeatured: false,
    tags: ["School Supplies"],
    image: "📚",
    coverColor: "from-blue-400 to-indigo-500",
    products: [
      { id: "p14", name: "Classmate Notebook A4 (6 pack)", price: 110, mrp: 120, category: "stationery", unit: "6 pcs", inStock: true, emoji: "📓" },
      { id: "p15", name: "Reynolds Pen (10 pack)", price: 85, mrp: 100, category: "stationery", unit: "10 pcs", inStock: true, emoji: "🖊️" },
      { id: "p16", name: "Apsara Pencil Box", price: 45, mrp: 50, category: "stationery", unit: "1 box", inStock: true, emoji: "✏️" },
      { id: "p17", name: "Gift Wrap Set", price: 65, mrp: 80, category: "gifts", unit: "1 set", inStock: true, emoji: "🎁" },
      { id: "p18", name: "Greeting Cards (5 pack)", price: 95, mrp: 110, category: "gifts", unit: "5 pcs", inStock: false, emoji: "💌" },
    ],
  },
  {
    id: "store-4",
    name: "Verma Household Mart",
    owner: "Sunil Verma",
    category: "household",
    categories: ["household", "grocery"],
    address: "8, Housing Board Colony",
    area: "Housing Board Colony",
    city: "Noida",
    distance: "0.5 km",
    rating: 4.3,
    reviewCount: 204,
    deliveryTime: "12–18 min",
    minOrder: 150,
    deliveryFee: 15,
    isOpen: false,
    isFeatured: false,
    tags: ["Household Essentials"],
    image: "🏠",
    coverColor: "from-yellow-400 to-orange-400",
    products: [
      { id: "p19", name: "Vim Dishwash Liquid 500ml", price: 88, mrp: 95, category: "household", unit: "500ml", inStock: true, emoji: "🫧" },
      { id: "p20", name: "Harpic Toilet Cleaner 500ml", price: 112, mrp: 125, category: "household", unit: "500ml", inStock: true, emoji: "🧹" },
      { id: "p21", name: "Surf Excel Easy Wash 1kg", price: 195, mrp: 215, category: "household", unit: "1kg", inStock: true, emoji: "🫧" },
      { id: "p22", name: "Lizol Floor Cleaner 500ml", price: 175, mrp: 195, category: "household", unit: "500ml", inStock: true, emoji: "🧽" },
    ],
  },
  {
    id: "store-5",
    name: "Singh Super Store",
    owner: "Harpreet Singh",
    category: "grocery",
    categories: ["grocery", "dairy", "household", "snacks"],
    address: "23, Main Market, Phase 2",
    area: "Phase 2",
    city: "Noida",
    distance: "0.9 km",
    rating: 4.7,
    reviewCount: 445,
    deliveryTime: "8–12 min",
    minOrder: 75,
    deliveryFee: 0,
    isOpen: true,
    isFeatured: true,
    tags: ["Express Delivery", "Free Delivery", "Top Rated"],
    image: "🏬",
    coverColor: "from-indigo-400 to-purple-500",
    products: [
      { id: "p23", name: "Parle-G Biscuits 800g", price: 85, mrp: 90, category: "snacks", unit: "800g", inStock: true, emoji: "🍪" },
      { id: "p24", name: "Maggi Noodles (12 pack)", price: 168, mrp: 180, category: "snacks", unit: "12x70g", inStock: true, emoji: "🍜" },
      { id: "p25", name: "Nestlé Milk 1L Tetra", price: 68, mrp: 72, category: "dairy", unit: "1L", inStock: true, emoji: "🥛" },
      { id: "p26", name: "Amul Paneer 200g", price: 95, mrp: 105, category: "dairy", unit: "200g", inStock: true, emoji: "🧀" },
    ],
  },
];

export const banners = [
  {
    id: "b1",
    title: "Free Delivery on First Order",
    subtitle: "Use code FIRST50",
    emoji: "🎉",
    gradient: "from-green-500 to-emerald-600",
  },
  {
    id: "b2",
    title: "Groceries in 10 Minutes",
    subtitle: "From stores near you",
    emoji: "⚡",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "b3",
    title: "Support Local Businesses",
    subtitle: "Shop from neighborhood stores",
    emoji: "🏪",
    gradient: "from-blue-500 to-indigo-600",
  },
];

export const recentOrders = [
  {
    id: "ORD-001",
    storeName: "Sharma Kirana Store",
    storeId: "store-1",
    items: ["Amul Butter 500g", "Tata Salt 1kg", "Mother Dairy Milk 500ml"],
    total: 335,
    status: "delivered",
    date: "Today, 2:30 PM",
    deliveryTime: "12 min",
  },
  {
    id: "ORD-002",
    storeName: "Priya Cosmetics",
    storeId: "store-2",
    items: ["Nivea Moisturizer 200ml", "Dove Soap (3 pack)"],
    total: 365,
    status: "out_for_delivery",
    date: "Today, 4:15 PM",
    deliveryTime: "Arriving in 5 min",
  },
];

export const shopOrders = [
  { id: "ORD-101", customer: "Rohit M.", items: 3, total: 485, status: "pending", time: "2 min ago" },
  { id: "ORD-102", customer: "Sneha K.", items: 5, total: 712, status: "preparing", time: "8 min ago" },
  { id: "ORD-103", customer: "Amit P.", items: 2, total: 234, status: "out_for_delivery", time: "15 min ago" },
  { id: "ORD-104", customer: "Kavya R.", items: 7, total: 1240, status: "delivered", time: "45 min ago" },
  { id: "ORD-105", customer: "Deepak S.", items: 4, total: 567, status: "delivered", time: "1 hr ago" },
];

export const deliveryOrders = [
  {
    id: "DEL-001",
    orderId: "ORD-101",
    customerName: "Rohit Mehta",
    customerAddress: "12, Sector 15, Noida",
    storeName: "Sharma Kirana Store",
    storeAddress: "12, Nehru Colony, Sector 15",
    items: 3,
    total: 485,
    distance: "1.2 km",
    earnings: 35,
    status: "available",
  },
  {
    id: "DEL-002",
    orderId: "ORD-102",
    customerName: "Sneha Khanna",
    customerAddress: "45, Sector 18, Noida",
    storeName: "Priya Cosmetics",
    storeAddress: "Shop 5, Market Complex, Sector 18",
    items: 5,
    total: 712,
    distance: "0.8 km",
    earnings: 30,
    status: "available",
  },
];

export const adminStats = {
  totalOrders: 1284,
  activeOrders: 47,
  totalRevenue: 284500,
  totalStores: 38,
  activeStores: 31,
  totalCustomers: 2840,
  totalDeliveries: 1108,
  avgDeliveryTime: "14 min",
};
